### ISSUE TITLE
Remove Windows dependency for esc keyboard buffer read to exit

### ISSUE THREAD

**Issue by dbenge** [AdobeAtAdobe/SimpleSensor#11]
## Expected Behavior
When you hit the escape key it should shutdown, regardless of OS.

## Actual Behavior
Currently depends on the msvcrt module, Windows only.

## Environment details (OS, Python/package versions, any other hardware)
- macOS, Linux

**Comment by maxakuru** [comment]
We'll need to do a full port to support macOS and Linux. Closing this for now.
